// Catálogo inicial con perfumes reales.
// Notas olfativas según la pirámide publicada por cada marca (resumidas a las principales).
// Precios: referencia aproximada en tiendas departamentales de México (MXN, IVA incluido); pueden variar.
// Duración y proyección: estimaciones generales, dependen de la piel y el clima.

// Fotos: 7 de Wikimedia Commons (licencia libre, autor citado) y 20 fotos de producto de las marcas vía Fragrantica (uso académico).
const IMAGENES = require('./imagenes.json');
const p = (o) => ({ disponible: 1, estado: 'Publicado', ...IMAGENES[o.nombre], ...o });

module.exports = [
  // ---------------- Oriental ----------------
  p({
    nombre: 'Black Opium', marca: 'Yves Saint Laurent', familia: 'Oriental', subfamilia: 'Oriental vainillado',
    concentracion: 'Eau de Parfum', ml: 90, precio: 3350, intensidad: 'Intensa', publico: 'Femenino',
    ocasiones: 'Cita,Evento formal', temporadas: 'Otoño,Invierno',
    notas_salida: 'Pera, pimienta rosa, flor de azahar', notas_corazon: 'Café, jazmín, almendra amarga',
    notas_fondo: 'Vainilla, pachulí, cedro', duracion: '8 – 10 horas', proyeccion: 'Moderada – alta',
    color: '#2A2228', anio: 2014, perfumista: 'Nathalie Lorson, Marie Salamagne, Olivier Cresp, Honorine Blanc',
    descripcion: 'Contraste entre la energía del café negro y la suavidad de la vainilla y las flores blancas. Un clásico moderno para la noche.',
  }),
  p({
    nombre: 'Good Girl', marca: 'Carolina Herrera', familia: 'Oriental', subfamilia: 'Oriental floral',
    concentracion: 'Eau de Parfum', ml: 80, precio: 2890, intensidad: 'Intensa', publico: 'Femenino',
    ocasiones: 'Cita,Evento formal', temporadas: 'Otoño,Invierno',
    notas_salida: 'Almendra, café, bergamota', notas_corazon: 'Nardo, jazmín sambac, rosa',
    notas_fondo: 'Haba tonka, cacao, vainilla', duracion: '8 – 10 horas', proyeccion: 'Alta',
    color: '#1E2A4A', anio: 2016, perfumista: 'Louise Turner, Quentin Bisch',
    descripcion: 'Flores blancas luminosas sobre un fondo oscuro de cacao y haba tonka. Seductor y con mucha presencia; su frasco en forma de tacón es icónico.',
  }),
  p({
    nombre: 'Le Male', marca: 'Jean Paul Gaultier', familia: 'Oriental', subfamilia: 'Oriental fougère',
    concentracion: 'Eau de Toilette', ml: 125, precio: 2350, intensidad: 'Moderada', publico: 'Masculino',
    ocasiones: 'Cita,Día a día', temporadas: 'Otoño,Invierno',
    notas_salida: 'Lavanda, menta, cardamomo, bergamota', notas_corazon: 'Canela, flor de azahar, comino',
    notas_fondo: 'Vainilla, haba tonka, sándalo', duracion: '6 – 8 horas', proyeccion: 'Moderada – alta',
    color: '#6E9CC4', anio: 1995, perfumista: 'Francis Kurkdjian',
    descripcion: 'Lavanda fresca y menta que se funden con vainilla y especias. Limpio y cálido a la vez, con una estela reconfortante.',
  }),
  p({
    nombre: 'Spicebomb', marca: 'Viktor&Rolf', familia: 'Oriental', subfamilia: 'Oriental especiado',
    concentracion: 'Eau de Toilette', ml: 90, precio: 2790, intensidad: 'Intensa', publico: 'Masculino',
    ocasiones: 'Cita,Evento formal', temporadas: 'Otoño,Invierno',
    notas_salida: 'Pimienta rosa, elemí, bergamota, pomelo', notas_corazon: 'Canela, azafrán, pimentón',
    notas_fondo: 'Tabaco, cuero, vetiver', duracion: '8 – 10 horas', proyeccion: 'Moderada – alta',
    color: '#4B5234', anio: 2012, perfumista: 'Olivier Polge',
    descripcion: 'Una explosión de especias calientes que se asienta en tabaco y cuero. Ideal para noches frías.',
  }),
  p({
    nombre: 'Baccarat Rouge 540', marca: 'Maison Francis Kurkdjian', familia: 'Oriental', subfamilia: 'Ambarado floral',
    concentracion: 'Eau de Parfum', ml: 70, precio: 7900, intensidad: 'Intensa', publico: 'Unisex',
    ocasiones: 'Evento formal,Cita', temporadas: 'Otoño,Invierno,Primavera',
    notas_salida: 'Azafrán, jazmín', notas_corazon: 'Madera de ámbar, ámbar gris',
    notas_fondo: 'Resina de abeto, cedro', duracion: '12 h +', proyeccion: 'Alta',
    color: '#B8574A', anio: 2015, perfumista: 'Francis Kurkdjian',
    descripcion: 'Aireado, mineral y ambarado, con un matiz dulce de azúcar quemado. Una de las fragancias de nicho más reconocibles, de estela muy duradera.',
  }),

  // ---------------- Gourmand ----------------
  p({
    nombre: 'La Vie Est Belle', marca: 'Lancôme', familia: 'Gourmand', subfamilia: 'Floral gourmand',
    concentracion: 'Eau de Parfum', ml: 100, precio: 3450, intensidad: 'Intensa', publico: 'Femenino',
    ocasiones: 'Cita,Día a día', temporadas: 'Otoño,Invierno',
    notas_salida: 'Grosella negra, pera', notas_corazon: 'Iris, jazmín, flor de azahar',
    notas_fondo: 'Praliné, vainilla, pachulí, haba tonka', duracion: '8 – 10 horas', proyeccion: 'Alta',
    color: '#D69AA3', anio: 2012, perfumista: 'Olivier Polge, Dominique Ropion, Anne Flipo',
    descripcion: 'Iris empolvado envuelto en praliné y vainilla. Dulce, femenino y muy persistente.',
  }),
  p({
    nombre: 'Angel', marca: 'Mugler', familia: 'Gourmand', subfamilia: 'Oriental gourmand',
    concentracion: 'Eau de Parfum', ml: 50, precio: 2850, intensidad: 'Intensa', publico: 'Femenino',
    ocasiones: 'Cita,Evento formal', temporadas: 'Invierno,Otoño',
    notas_salida: 'Algodón de azúcar, melón, coco, bergamota', notas_corazon: 'Miel, frutos rojos, jazmín',
    notas_fondo: 'Pachulí, caramelo, vainilla, chocolate', duracion: '12 h +', proyeccion: 'Alta',
    color: '#3B5BA5', anio: 1992, perfumista: 'Olivier Cresp, Yves de Chiris',
    descripcion: 'El perfume que inventó la familia gourmand: caramelo y chocolate con un pachulí intenso. Inconfundible.',
  }),
  p({
    nombre: 'Cloud', marca: 'Ariana Grande', familia: 'Gourmand', subfamilia: 'Gourmand cremoso',
    concentracion: 'Eau de Parfum', ml: 100, precio: 1390, intensidad: 'Moderada', publico: 'Femenino',
    ocasiones: 'Día a día,Cita', temporadas: 'Primavera,Otoño',
    notas_salida: 'Lavanda, pera, bergamota', notas_corazon: 'Crema batida, praliné, coco',
    notas_fondo: 'Almizcle, maderas cremosas', duracion: '6 – 8 horas', proyeccion: 'Moderada',
    color: '#B9C4E4', anio: 2018, perfumista: 'Clément Gavarry',
    descripcion: 'Dulce y aireado, como crema batida con un toque de lavanda. Muy popular por su buena relación calidad-precio.',
  }),

  // ---------------- Floral ----------------
  p({
    nombre: "J'adore", marca: 'Dior', familia: 'Floral', subfamilia: 'Floral frutal',
    concentracion: 'Eau de Parfum', ml: 100, precio: 4150, intensidad: 'Moderada', publico: 'Femenino',
    ocasiones: 'Evento formal,Oficina', temporadas: 'Primavera,Verano',
    notas_salida: 'Pera, melón, mandarina', notas_corazon: 'Jazmín, rosa, nardo',
    notas_fondo: 'Almizcle, vainilla, cedro', duracion: '6 – 8 horas', proyeccion: 'Moderada',
    color: '#DDB250', anio: 1999, perfumista: 'Calice Becker',
    descripcion: 'Un ramo luminoso de jazmín y rosa con frutas jugosas. Elegante y fácil de llevar en cualquier momento del día.',
  }),
  p({
    nombre: 'Chance Eau Tendre', marca: 'Chanel', familia: 'Floral', subfamilia: 'Floral frutal',
    concentracion: 'Eau de Toilette', ml: 100, precio: 3750, intensidad: 'Suave', publico: 'Femenino',
    ocasiones: 'Día a día,Oficina', temporadas: 'Primavera,Verano',
    notas_salida: 'Pomelo, membrillo', notas_corazon: 'Jacinto, jazmín',
    notas_fondo: 'Almizcle blanco, iris, cedro', duracion: '4 – 6 horas', proyeccion: 'Suave',
    color: '#EDB3C2', anio: 2010, perfumista: 'Jacques Polge',
    descripcion: 'Fresco, frutal y delicado. Una versión tierna de Chance pensada para el día.',
  }),
  p({
    nombre: 'Daisy', marca: 'Marc Jacobs', familia: 'Floral', subfamilia: 'Floral frutal',
    concentracion: 'Eau de Toilette', ml: 100, precio: 2450, intensidad: 'Suave', publico: 'Femenino',
    ocasiones: 'Día a día,Oficina', temporadas: 'Primavera,Verano',
    notas_salida: 'Fresa, violeta, pomelo rosado', notas_corazon: 'Gardenia, jazmín, violeta',
    notas_fondo: 'Almizcle, vainilla, maderas blancas', duracion: '4 – 6 horas', proyeccion: 'Suave',
    color: '#E6D08F', anio: 2007, perfumista: 'Alberto Morillas',
    descripcion: 'Alegre y juvenil, con fresa y flores blancas. Su frasco con margaritas es de los más reconocibles.',
  }),
  p({
    nombre: 'Bloom', marca: 'Gucci', familia: 'Floral', subfamilia: 'Flores blancas',
    concentracion: 'Eau de Parfum', ml: 100, precio: 3250, intensidad: 'Moderada', publico: 'Femenino',
    ocasiones: 'Cita,Oficina', temporadas: 'Primavera',
    notas_salida: 'Enredadera de Rangún', notas_corazon: 'Jazmín sambac',
    notas_fondo: 'Nardo', duracion: '6 – 8 horas', proyeccion: 'Moderada',
    color: '#E4B9B4', anio: 2017, perfumista: 'Alberto Morillas',
    descripcion: 'Un jardín de flores blancas: nardo y jazmín cremosos con un toque verde. Romántico y natural.',
  }),
  p({
    nombre: 'N°5', marca: 'Chanel', familia: 'Floral', subfamilia: 'Floral aldehídico',
    concentracion: 'Eau de Parfum', ml: 100, precio: 4650, intensidad: 'Intensa', publico: 'Femenino',
    ocasiones: 'Evento formal', temporadas: 'Otoño,Invierno',
    notas_salida: 'Aldehídos, ylang-ylang, neroli, bergamota', notas_corazon: 'Rosa de mayo, jazmín, iris',
    notas_fondo: 'Sándalo, vainilla, vetiver', duracion: '8 – 10 horas', proyeccion: 'Moderada – alta',
    color: '#E3C98C', anio: 1986, perfumista: 'Jacques Polge (sobre el original de Ernest Beaux, 1921)',
    descripcion: 'Versión Eau de Parfum del perfume más famoso de la historia: aldehídos chispeantes sobre rosa y jazmín. (Registro en borrador para mostrar el estado.)',
    estado: 'Borrador',
  }),

  // ---------------- Cítrico ----------------
  p({
    nombre: 'Light Blue', marca: 'Dolce&Gabbana', familia: 'Cítrico', subfamilia: 'Cítrico frutal',
    concentracion: 'Eau de Toilette', ml: 100, precio: 2390, intensidad: 'Suave', publico: 'Femenino',
    ocasiones: 'Día a día,Deporte', temporadas: 'Verano,Primavera',
    notas_salida: 'Limón siciliano, manzana, cedro', notas_corazon: 'Bambú, jazmín, rosa blanca',
    notas_fondo: 'Cedro, ámbar, almizcle', duracion: '4 – 6 horas', proyeccion: 'Moderada',
    color: '#94BEDB', anio: 2001, perfumista: 'Olivier Cresp',
    descripcion: 'Limón siciliano y manzana verde que evocan el Mediterráneo. El perfume de verano por excelencia.',
  }),
  p({
    nombre: 'CK One', marca: 'Calvin Klein', familia: 'Cítrico', subfamilia: 'Cítrico aromático',
    concentracion: 'Eau de Toilette', ml: 100, precio: 1250, intensidad: 'Suave', publico: 'Unisex',
    ocasiones: 'Día a día,Oficina,Deporte', temporadas: 'Primavera,Verano',
    notas_salida: 'Limón, bergamota, piña, cardamomo', notas_corazon: 'Jazmín, violeta, nuez moscada',
    notas_fondo: 'Almizcle, cedro, té verde, ámbar', duracion: '4 – 6 horas', proyeccion: 'Suave',
    color: '#C3CFBC', anio: 1994, perfumista: 'Alberto Morillas, Harry Fremont',
    descripcion: 'El primer gran perfume unisex: limpio, cítrico y con té verde. Versátil y accesible.',
  }),
  p({
    nombre: 'Colonia', marca: 'Acqua di Parma', familia: 'Cítrico', subfamilia: 'Cítrico aromático',
    concentracion: 'Eau de Cologne', ml: 100, precio: 3690, intensidad: 'Suave', publico: 'Unisex',
    ocasiones: 'Oficina,Día a día', temporadas: 'Primavera,Verano',
    notas_salida: 'Limón, naranja dulce, bergamota', notas_corazon: 'Lavanda, verbena, romero, rosa',
    notas_fondo: 'Vetiver, sándalo, pachulí', duracion: '2 – 4 horas', proyeccion: 'Suave',
    color: '#DDB13C', anio: 1916, perfumista: null,
    descripcion: 'La colonia italiana clásica: cítricos soleados y hierbas aromáticas. Elegancia sencilla desde principios del siglo XX.',
  }),
  p({
    nombre: 'Lime Basil & Mandarin', marca: 'Jo Malone London', familia: 'Cítrico', subfamilia: 'Cítrico aromático',
    concentracion: 'Eau de Cologne', ml: 100, precio: 3450, intensidad: 'Suave', publico: 'Unisex',
    ocasiones: 'Oficina,Día a día', temporadas: 'Primavera,Verano',
    notas_salida: 'Lima, mandarina, bergamota', notas_corazon: 'Albahaca, tomillo, lila',
    notas_fondo: 'Vetiver, pachulí, ámbar', duracion: '2 – 4 horas', proyeccion: 'Suave',
    color: '#D6CDB4', anio: 1999, perfumista: 'Jo Malone',
    descripcion: 'Lima fresca con albahaca aromática. Una firma de la casa, ideal para combinar con otras fragancias.',
  }),

  // ---------------- Acuático ----------------
  p({
    nombre: 'Acqua di Giò', marca: 'Giorgio Armani', familia: 'Acuático', subfamilia: 'Acuático aromático',
    concentracion: 'Eau de Toilette', ml: 100, precio: 2750, intensidad: 'Moderada', publico: 'Masculino',
    ocasiones: 'Día a día,Oficina', temporadas: 'Verano,Primavera',
    notas_salida: 'Lima, limón, bergamota, neroli', notas_corazon: 'Notas marinas, jazmín, romero, durazno',
    notas_fondo: 'Almizcle blanco, cedro, musgo de roble, pachulí', duracion: '6 – 8 horas', proyeccion: 'Moderada',
    color: '#9DB2BD', anio: 1996, perfumista: 'Alberto Morillas, Annick Menardo, Christian Dussoulier',
    descripcion: 'Brisa marina con cítricos y romero. Uno de los perfumes masculinos más vendidos del mundo.',
  }),
  p({
    nombre: 'Cool Water', marca: 'Davidoff', familia: 'Acuático', subfamilia: 'Acuático fougère',
    concentracion: 'Eau de Toilette', ml: 125, precio: 990, intensidad: 'Moderada', publico: 'Masculino',
    ocasiones: 'Deporte,Día a día', temporadas: 'Verano',
    notas_salida: 'Notas marinas, menta, lavanda, cilantro', notas_corazon: 'Sándalo, neroli, geranio, jazmín',
    notas_fondo: 'Almizcle, musgo de roble, cedro, ámbar', duracion: '4 – 6 horas', proyeccion: 'Moderada',
    color: '#2F7CAD', anio: 1988, perfumista: 'Pierre Bourdon',
    descripcion: 'Pionero de los perfumes acuáticos: menta y lavanda frescas. Excelente precio para uso diario.',
  }),
  p({
    nombre: "L'Eau d'Issey pour Homme", marca: 'Issey Miyake', familia: 'Acuático', subfamilia: 'Acuático cítrico',
    concentracion: 'Eau de Toilette', ml: 125, precio: 2290, intensidad: 'Moderada', publico: 'Masculino',
    ocasiones: 'Oficina,Día a día', temporadas: 'Verano,Primavera',
    notas_salida: 'Yuzu, limón, bergamota, ciprés', notas_corazon: 'Nuez moscada, nenúfar, azafrán',
    notas_fondo: 'Vetiver, sándalo, tabaco, almizcle', duracion: '6 – 8 horas', proyeccion: 'Moderada',
    color: '#B4C4CD', anio: 1994, perfumista: 'Jacques Cavallier Belletrud',
    descripcion: 'Yuzu y agua con un fondo amaderado seco. Fresco pero sofisticado, muy adecuado para la oficina.',
  }),
  p({
    nombre: 'Voyage', marca: 'Nautica', familia: 'Acuático', subfamilia: 'Acuático verde',
    concentracion: 'Eau de Toilette', ml: 100, precio: 650, intensidad: 'Suave', publico: 'Masculino',
    ocasiones: 'Deporte,Día a día', temporadas: 'Verano,Primavera',
    notas_salida: 'Hoja verde, manzana', notas_corazon: 'Loto, mimosa, notas acuáticas',
    notas_fondo: 'Cedro, almizcle, ámbar, musgo de roble', duracion: '2 – 4 horas', proyeccion: 'Suave',
    color: '#3E6A4E', anio: 2006, perfumista: 'Maurice Roucel',
    descripcion: 'Manzana verde y loto con aire marino. Una opción económica y agradable para el calor.',
  }),

  // ---------------- Amaderado ----------------
  p({
    nombre: 'Sauvage', marca: 'Dior', familia: 'Amaderado', subfamilia: 'Amaderado aromático',
    concentracion: 'Eau de Toilette', ml: 100, precio: 3290, intensidad: 'Intensa', publico: 'Masculino',
    ocasiones: 'Día a día,Cita,Oficina', temporadas: 'Primavera,Verano,Otoño,Invierno',
    notas_salida: 'Bergamota de Calabria, pimienta', notas_corazon: 'Pimienta de Sichuan, lavanda, pimienta rosa, geranio',
    notas_fondo: 'Ambroxan, cedro, ládano', duracion: '8 – 10 horas', proyeccion: 'Alta',
    color: '#253A55', anio: 2015, perfumista: 'François Demachy',
    descripcion: 'Bergamota jugosa y ambroxan con mucha proyección. Versátil para todo el año; uno de los más vendidos de la última década.',
  }),
  p({
    nombre: 'Bleu de Chanel', marca: 'Chanel', familia: 'Amaderado', subfamilia: 'Amaderado aromático',
    concentracion: 'Eau de Parfum', ml: 100, precio: 3950, intensidad: 'Moderada', publico: 'Masculino',
    ocasiones: 'Oficina,Evento formal,Cita', temporadas: 'Primavera,Verano,Otoño,Invierno',
    notas_salida: 'Pomelo, limón, menta, pimienta rosa', notas_corazon: 'Jengibre, jazmín, nuez moscada',
    notas_fondo: 'Incienso, cedro, sándalo, pachulí', duracion: '8 – 10 horas', proyeccion: 'Moderada – alta',
    color: '#1F2B3E', anio: 2014, perfumista: 'Jacques Polge',
    descripcion: 'Cítricos frescos que evolucionan hacia incienso y sándalo. Elegante y seguro para cualquier ocasión.',
  }),
  p({
    nombre: "Terre d'Hermès", marca: 'Hermès', familia: 'Amaderado', subfamilia: 'Amaderado mineral',
    concentracion: 'Eau de Toilette', ml: 100, precio: 3350, intensidad: 'Moderada', publico: 'Masculino',
    ocasiones: 'Oficina,Evento formal', temporadas: 'Otoño,Primavera',
    notas_salida: 'Naranja, pomelo', notas_corazon: 'Pimienta, pelargonio, pedernal',
    notas_fondo: 'Vetiver, cedro, pachulí, benjuí', duracion: '8 – 10 horas', proyeccion: 'Moderada',
    color: '#C4682C', anio: 2006, perfumista: 'Jean-Claude Ellena',
    descripcion: 'Naranja amarga y vetiver con un acorde mineral de piedra. Sobrio, terroso y muy refinado.',
  }),
  p({
    nombre: '1 Million', marca: 'Paco Rabanne', familia: 'Amaderado', subfamilia: 'Amaderado especiado',
    concentracion: 'Eau de Toilette', ml: 100, precio: 2650, intensidad: 'Intensa', publico: 'Masculino',
    ocasiones: 'Cita,Evento formal', temporadas: 'Otoño,Invierno',
    notas_salida: 'Pomelo, menta, mandarina roja', notas_corazon: 'Canela, rosa, especias',
    notas_fondo: 'Cuero, ámbar, maderas, pachulí', duracion: '8 – 10 horas', proyeccion: 'Alta',
    color: '#C9A128', anio: 2008, perfumista: 'Christophe Raynaud, Olivier Pescheux, Michel Girard',
    descripcion: 'Canela y cuero dulce en un frasco con forma de lingote de oro. Llamativo y pensado para salir de noche.',
  }),
  p({
    nombre: 'Santal 33', marca: 'Le Labo', familia: 'Amaderado', subfamilia: 'Amaderado cuero',
    concentracion: 'Eau de Parfum', ml: 50, precio: 6900, intensidad: 'Moderada', publico: 'Unisex',
    ocasiones: 'Oficina,Día a día', temporadas: 'Otoño,Primavera',
    notas_salida: 'Cardamomo, violeta', notas_corazon: 'Iris, papiro',
    notas_fondo: 'Sándalo australiano, cuero, cedro', duracion: '8 – 10 horas', proyeccion: 'Moderada',
    color: '#C5B494', anio: 2011, perfumista: 'Frank Voelkl',
    descripcion: 'Sándalo cremoso y cuero suave con un toque de violeta. Un icono del perfume de nicho, sobrio y adictivo.',
  }),
  p({
    nombre: 'Oud Wood', marca: 'Tom Ford', familia: 'Amaderado', subfamilia: 'Amaderado oud',
    concentracion: 'Eau de Parfum', ml: 50, precio: 6950, intensidad: 'Moderada', publico: 'Unisex',
    ocasiones: 'Evento formal,Cita', temporadas: 'Otoño,Invierno',
    notas_salida: 'Palisandro, cardamomo, pimienta de Sichuan', notas_corazon: 'Oud, sándalo, vetiver',
    notas_fondo: 'Haba tonka, vainilla, ámbar', duracion: '6 – 8 horas', proyeccion: 'Moderada',
    color: '#4A3325', anio: 2007, perfumista: 'Richard Herpin',
    descripcion: 'Una interpretación suave y accesible del oud, con especias y maderas cálidas. Lujoso sin ser pesado.',
  }),
];
